version: '3.4'

services:

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: smartbear
      POSTGRES_PASSWORD: password
      POSTGRES_DB: smartbeardb
    ports:
      - "5432:5432"
  api:
    image: smartbear-docker-app:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      DB_TYPE: postgres
      DATABASE_URL: postgres://smartbear:password@postgres:5432/smartbeardb
      NODE_ENV: development
      PORT: 3000
    depends_on:
      - postgres
    ports:
      - "3000:3000"
